# Header
menu:
  Home: /
  Archive: /archives
  Zhihu: https://www.zhihu.com/people/hi.leiquan
  Github: https://github.com/leiquan
  LinkedIn: https://www.linkedin.com/in/leiquan/
  Facebook: https://www.facebook.com/hi.leiquan


# Content
excerpt_link: 阅读全文
fancybox: true

# Sidebar
sidebar: right

widgets:
  - avatar
  - category
  - archive
  - recent_posts
  - tagcloud
  - links

# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
google_analytics:
favicon: /css/images/me.jpg
twitter:
google_plus:
fb_admins:
fb_app_id:
